- fix in checking is netforking is up.
Changed files:
    ypserv-yppasswdd.init -> 1.4
    ypserv-ypserv.init -> 1.4

diff --git a/ypserv-yppasswdd.init b/ypserv-yppasswdd.init
--- a/ypserv-yppasswdd.init
+++ b/ypserv-yppasswdd.init
@@ -21,7 +21,10 @@
 [ -f /etc/sysconfig/yppasswdd ] && . /etc/sysconfig/yppasswdd
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Yppasswdd can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
diff --git a/ypserv-ypserv.init b/ypserv-ypserv.init
--- a/ypserv-ypserv.init
+++ b/ypserv-ypserv.init
@@ -23,7 +23,10 @@
 [ -f /etc/sysconfig/ypserv-ypserv ] && . /etc/sysconfig/ypserv-ypserv
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Ypserv service can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
